### PR TITLE
fix: stop spamming users when crashing, fix .length of undefined when adding contribution

### LINKED ISSUE #266: Getting into the loop of adding
**Describe the bug**
Please, check: https://github.com/skywinder/ActionSheetPicker-3.0/pull/435
I lock conversation since bot get into the loop of adding new comments.

**To Reproduce**
Look at the commetns there
looks like it started by the phrase:
"@all-contributors please add @all-contributors for docs"

**Expected behavior**
Bot have to answer once.

**Screenshots**

image

image

### PR DESCRIPTION
**Pull request by jakebolam**
Fixes #266 and #270 introduced by  #249

### CODE REVIEW

File: src/tasks/processIssueComment/Repository/index.js [hunk 1]
```diff
@@ -41,7 +41,7 @@ class Repository {
             }
         } catch (error) {
             if (error.status === 404) {
-                throw new ResourceNotFoundError(filePath, this.full_name)
+                throw new ResourceNotFoundError(filePath, this.getFullname())
```
Comment (jakebolam) [inline src/tasks/processIssueComment/Repository/index.js]: noticed this was working either, fixed as well

**Comment by gr2m** [comment]
Can you maybe add a test to make sure we won't break it again?
