### PR TITLE
fix: handle error when branch already exists

### LINKED ISSUE #16: Handle case where branch already exists
**Describe the bug**
Bot currently crashes with `We had trouble processing your request. Please try again later. When the contributor branch already exists

**To Reproduce**
1. Comment and say `@AllContributorsBot please add jakebolam for code, doc and infra`
2. Wait for pull reuqest to be created
3. Comment again and say `@AllContributorsBotDev please add jakebolam for code, doc and infra`
4. See crash

**Expected behavior**
Should return and say a branch/PR is already open.

**Screenshots**

**Additional context**
After we fix this bug, it is likely we will expose the bug branch exist, but PR is not open. We should be wary of this case too. 

sentry error of one such case: `Error: Reference already exists` 
https://sentry.io/all-contributors/github-bot/issues/844367677/?query=is%3Aunresolved

### PR DESCRIPTION
**Pull request by sinchang**
fixes #16

### CODE REVIEW

File: src/utils/errors.js [hunk 1]
```diff
@@ -21,8 +21,16 @@ class UserNotFoundError extends AllContributorBotError {
     }
 }
 
+class ReferenceExistsError extends AllContributorBotError {
+    constructor() {
+        super(`A branch or Pull Request is already open.`)
```
Comment (sinchang) [inline src/utils/errors.js]: error message any suggestions?

File: test/Repository/index.test.js [hunk 2]
```diff
@@ -101,4 +102,43 @@ describe('Repository', () => {
...
+
+        nock('https://api.github.com')
+            .post(
+                `/repos/all-contributors/all-contributors-bot/git/refs`,
+                verifyBody,
+            )
+            .reply(422)
+
+        const error = await rejectionOf(
+            repository.createPullRequestFromFiles({
```
Comment (jakebolam) [inline test/Repository/index.test.js]: When we are creating the pull request and the branch exists can we recover somehow?

E.g. delete the branch then create. Or Maybe have a unique I'd for the branch we are creating (using UUID)?

File: src/Repository/index.js [hunk 3]
```diff
@@ -72,14 +75,21 @@ class Repository {
...
+            // https://octokit.github.io/rest.js/#api-Git-createRef
+            await this.github.git.createRef({
+                owner: this.owner,
+                repo: this.repo,
+                ref: `refs/heads/${branchName}`,
+                sha: fromSha,
+            })
+        } catch (error) {
+            if (error.code === 422) {
+                throw new ReferenceExistsError()
```
Comment (jakebolam) [inline src/Repository/index.js]: :+1:

File: src/utils/errors.js (hunk 1 above)
Comment (jakebolam) [reply src/utils/errors.js]: Perhaps `Branch ${branch} already exists`

File: test/Repository/index.test.js (hunk 2 above)
Comment (sinchang) [reply test/Repository/index.test.js]: I prefer the second suggestion.

Comment (sinchang) [reply test/Repository/index.test.js]: Create a unique branch so that it is the easiest and the smallest to change

File: src/utils/errors.js (hunk 1 above)
Comment (Berkmann18) [reply src/utils/errors.js]: ^ so at least it indicates which branch.

File: test/Repository/index.test.js (hunk 2 above)
Comment (Berkmann18) [reply test/Repository/index.test.js]: If the branch is already open, I think that the bot should be able to (re)-use it.
If the PR is already open then it shouldn't be doing anything **unless** it's changing/adding/removing something else.

**Comment by sinchang** [comment]
some cases:

1. branch not exists and pr not open - create branch and open pr

2. branch exists and pr not open - update branch and open pr

3. branch exists and pr open - update branch

4. branch exists and pr closed - update branch and create a new pr

**Comment by Berkmann18** [comment]
Here's one more case (although casi unlikely to occur):
5. branch doesn't exist but there's a pr open - move the pr to the correct branch

I think that's all possible cases unless we're missing a variable/factor?

File: src/Repository/index.js [hunk 4]
```diff
@@ -83,21 +83,13 @@ class Repository {
...
-            await this.github.git.createRef({
-                owner: this.owner,
-                repo: this.repo,
-                ref: `refs/heads/${branchName}`,
-                sha: fromSha,
-            })
-
-            return false
-        } catch (error) {
-            // branch already exists
```
Comment (Berkmann18) [inline src/Repository/index.js]: What would be the advantage and reason for not handling situations where `this.github.git.createRef` fails and throws an error?

File: src/Repository/index.js [hunk 5]
```diff
@@ -140,41 +150,41 @@ class Repository {
...
-        title,
-        body,
-        filesByPath,
-        branchName,
-        defaultBranch,
-    }) {
-        await this.createBranch({ branchName, defaultBranch })
+    async createPullRequestFromFiles({ title, body, filesByPath, branchName }) {
+        if (this.basedBranch === this.defaultBranch)
+            await this.createBranch(branchName)
```
Comment (jakebolam) [inline src/Repository/index.js]: [nb] drop await, method is sync

File: src/Repository/index.js [hunk 6]
```diff
@@ -140,41 +150,41 @@ class Repository {
...
-            defaultBranch,
-        })
+        try {
+            const pullRequestURL = await this.createPullRequest({
+                title,
+                body,
+                branchName,
+            })
+            return pullRequestURL
+        } catch (error) {
```
Comment (jakebolam) [inline src/Repository/index.js]: This catch and error thrown should come from the `createPullReuqest method`

File: src/Repository/index.js [hunk 7]
```diff
@@ -140,41 +150,41 @@ class Repository {
...
+            if (error.status === 422)
+                throw new AllContributorBotError('Pull request is already open')
```
Comment (jakebolam) [inline src/Repository/index.js]: Can we add a link?
`I've updated the [pull request](INSERT_LINK_HERE) you have open.`

I don't think this should error too, could we handle this as a reply case here: (https://github.com/all-contributors/all-contributors-bot/blob/master/src/processIssueComment.js#L65-L67) e.g. can throw the error, but catch it here

File: src/Repository/index.js [hunk 8]
```diff
@@ -61,17 +71,17 @@ class Repository {
         return multipleFilesByPath
     }
 
-    async getHeadRef(defaultBranch) {
+    async getHeadRef(branchName) {
         const result = await this.github.git.getRef({
```
Comment (jakebolam) [inline src/Repository/index.js]: Instead of checking 404 above when called.

Can we throw an error here? (BranchAlreadyExists) and catch that

File: src/processIssueComment.js [hunk 9]
```diff
@@ -68,14 +66,29 @@ async function processAddContributor({
...
         ...context.repo(),
         github: context.github,
+        defaultBranch,
     })
+
+    try {
+        await repository.getHeadRef(branchName)
+        repository.setBasedBranch(branchName)
+    } catch (error) {
+        if (error.status !== 404) throw error
```
Comment (jakebolam) [inline src/processIssueComment.js]: `if (error instance of BranchAlreadyExists)`

File: src/processIssueComment.js [hunk 10]
```diff
@@ -68,14 +66,29 @@ async function processAddContributor({
...
+    const { who, action, contributions } = parseComment(commentBody)
+    const branchName = `all-contributors/add-${who}`
+    const defaultBranch = context.payload.repository.default_branch
     const repository = new Repository({
         ...context.repo(),
         github: context.github,
+        defaultBranch,
     })
+
+    try {
```
Comment (jakebolam) [inline src/processIssueComment.js]: This block should happen after fetching config IMO

Comment (jakebolam) [reply src/processIssueComment.js]: This block should happen inside the `processAddContributor` block. (For future support of other actions)

File: test/index-e2e.test.js [hunk 11]
```diff
@@ -273,4 +304,148 @@ describe('All Contributors app - End to end', () => {
         )
         expect(error instanceof Error).toBeTruthy()
     })
+
+    test('Happy path, add correct new contributor, but branch exists', async () => {
```
Comment (jakebolam) [inline test/index-e2e.test.js]: [nb] and pr closed

File: src/Repository/index.js [hunk 12]
```diff
@@ -61,17 +71,17 @@ class Repository {
...
-            ref: `heads/${defaultBranch}`,
+            ref: `heads/${branchName}`,
         })
         return result.data.object.sha
     }
 
-    async createBranch({ branchName, defaultBranch }) {
-        const fromSha = await this.getHeadRef(defaultBranch)
+    async createBranch(branchName) {
+        const fromSha = await this.getHeadRef(this.defaultBranch)
```
Comment (jakebolam) [inline src/Repository/index.js]: [nb] can we leave this as a parameter? `createBranch({ newBranchName, fromBranchName })`

File: src/Repository/index.js [hunk 13]
```diff
@@ -140,41 +150,41 @@ class Repository {
...
-    async createPullRequestFromFiles({
-        title,
-        body,
-        filesByPath,
-        branchName,
-        defaultBranch,
-    }) {
-        await this.createBranch({ branchName, defaultBranch })
+    async createPullRequestFromFiles({ title, body, filesByPath, branchName }) {
+        if (this.basedBranch === this.defaultBranch)
```
Comment (jakebolam) [inline src/Repository/index.js]: I get what your trying to go for here but it took me a while to understand.
Could we do something like
```
const branchNameExists = branchName === this.basedBranch
if (!branchNameExists) {
```

File: src/Repository/index.js [hunk 14]
```diff
@@ -61,17 +71,17 @@ class Repository {
         return multipleFilesByPath
     }
 
-    async getHeadRef(defaultBranch) {
+    async getHeadRef(branchName) {
```
Comment (jakebolam) [inline src/Repository/index.js]: This method should now just be called `getRef`

File: src/Repository/index.js [hunk 15]
```diff
@@ -1,16 +1,25 @@
...
 
     getFullname() {
         return `${this.owner}/${this.repo}`
     }
 
+    setBasedBranch(branchName) {
+        this.basedBranch = branchName
+    }
+
     async getFile(filePath) {
```
Comment (jakebolam) [inline src/Repository/index.js]: I wonder how we can take the latest master file and overwrite the current branch :think: like a rebase

Comment (jakebolam) [reply src/Repository/index.js]: We probably shouldn't address this here. This is probably a whole ticket in itself. #62.
I'm interested in hearing how you would solve this problem tho.

**Comment by jakebolam** [comment]
@sinchang are you ok if I get this over the line?

**Comment by jakebolam** [comment]
@sinchang THIS IS AWESOME, THANK YOU

**Comment by jakebolam** [comment]
@all-contributors please add @sinchang for ideas
