### PR TITLE
fix: usernames can have brackets

### LINKED ISSUE #33: Usernames with brackets crash the bot
**Describe the bug**
`@allcontributors[bot] add allcontributors[bot] for doc`

**To Reproduce**
screen shot 2019-01-15 at 1 37 23 am

**Expected behavior**
To add a PR to add the user with brackets

**Additional context**
From sentry:
`HttpError: refs/heads/all-contributors/add-allcontributors[bot] is not a valid ref name.`

Looks like its trying to create the branch/ref with invalid semantics. The name for the branch will need to be escaped.

### PR DESCRIPTION
**Pull request by jakebolam**
Fixes #33

### CODE REVIEW

File: src/utils/git/getSafeRef.js [hunk 1]
```diff
@@ -0,0 +1,13 @@
+/* eslint-disable no-useless-escape */
+
+function getSafeRef(ref) {
```
Comment (jakebolam) [inline src/utils/git/getSafeRef.js]: This is horrendous, I'm open to comments for follow-up PRs
